set_property IOSTANDARD LVCMOS33 [get_ports ad_clk1]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk2]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_in2[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports reset_n]


set_property PACKAGE_PIN K14 [get_ports ad_clk1]
set_property PACKAGE_PIN L15 [get_ports {ad_in1[0]}]
set_property PACKAGE_PIN G14 [get_ports {ad_in1[1]}]
set_property PACKAGE_PIN J14 [get_ports {ad_in1[2]}]
set_property PACKAGE_PIN F16 [get_ports {ad_in1[3]}]
set_property PACKAGE_PIN H15 [get_ports {ad_in1[4]}]
set_property PACKAGE_PIN D18 [get_ports {ad_in1[5]}]
set_property PACKAGE_PIN E17 [get_ports {ad_in1[6]}]
set_property PACKAGE_PIN D19 [get_ports {ad_in1[7]}]
set_property PACKAGE_PIN E18 [get_ports {ad_in1[8]}]
set_property PACKAGE_PIN F17 [get_ports {ad_in1[9]}]
set_property PACKAGE_PIN D20 [get_ports {ad_in1[10]}]
set_property PACKAGE_PIN G17 [get_ports {ad_in1[11]}]
set_property PACKAGE_PIN G20 [get_ports {ad_in2[0]}]
set_property PACKAGE_PIN G19 [get_ports {ad_in2[1]}]
set_property PACKAGE_PIN H20 [get_ports {ad_in2[2]}]
set_property PACKAGE_PIN G18 [get_ports {ad_in2[3]}]
set_property PACKAGE_PIN J20 [get_ports {ad_in2[4]}]
set_property PACKAGE_PIN H16 [get_ports {ad_in2[5]}]
set_property PACKAGE_PIN H18 [get_ports {ad_in2[6]}]
set_property PACKAGE_PIN J19 [get_ports {ad_in2[7]}]
set_property PACKAGE_PIN J18 [get_ports {ad_in2[8]}]
set_property PACKAGE_PIN K19 [get_ports {ad_in2[9]}]
set_property PACKAGE_PIN K18 [get_ports {ad_in2[10]}]
set_property PACKAGE_PIN H17 [get_ports {ad_in2[11]}]
set_property PACKAGE_PIN T14 [get_ports led]
set_property PACKAGE_PIN K16 [get_ports ad_clk2]


set_property PACKAGE_PIN F20 [get_ports reset_n]



